server:
 port: 8080
spring:
 datasource:
   url: "jdbc:postgresql://localhost:5432/spring"
   username: "postgres"
   password: ""
   driver-class-name: "org.postgresql.Driver"
 jpa:
  show-sql: true
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
